- name: Set up dev environment
  ansible.builtin.import_playbook: imported_playbooks/Dev-Environment-Setup/ansible/playbook.yaml

- name: Set up server node
  hosts: server_hosts
  tasks:
    - name: Install Docker
      ansible.builtin.include_role:
        name: install_docker

    - name: Install Terraform
      ansible.builtin.include_role:
        name: install_terraform

    - name: Install system-wide Tailscale
      ansible.builtin.include_role:
        name: install_system_tailscale

    - name: Set up iptables rules
      ansible.builtin.include_role:
        name: setup_iptables

    - name: Set up for Compose
      ansible.builtin.include_role:
        name: setup_compose

    - name: Set up for Terraform
      ansible.builtin.include_role:
        name: setup_terraform

    - name: Set up for system-wide Tailscale (SSH)
      ansible.builtin.include_role:
        name: setup_system_tailscale
