- name: Set up dev environment
  ansible.builtin.import_playbook: imported_playbooks/Dev-Environment-Setup/ansible/playbook.yml

- name: Set up server node
  hosts: server_hosts
  become: true
  tasks:
    - name: Install Docker
      include_role:
        name: install_docker
