- name: Set up dev environment
  ansible.builtin.import_playbook: imported_playbooks/Dev-Environment-Setup/ansible/playbook.yaml

- name: Set up server node
  hosts: server_hosts
  become: true
  tasks:
    - name: Install Docker
      include_role:
        name: install_docker

    - name: Install Terraform
      include_role:
        name: install_terraform

    - name: Configure for EJBCA
      include_role:
        name: ejbca_preconfigure
