- name: Ensure directory is present
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/Documents/server"
    state: directory
    mode: '0755'

- name: Clone git repository
  ansible.builtin.git:
    repo: 'https://github.com/Nicholas-Ho/homelab-compose.git'
    dest: "{{ ansible_facts['user_dir'] }}/Documents/server/compose"

- name: Define data directory
  ansible.builtin.set_fact:
    data_dir: "{{ ansible_facts['user_dir'] }}/Documents/server/.data"

- name: Ensure data directories are present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    # === EJBCA ===
    - "{{ data_dir }}/ejbca"
    - "{{ data_dir }}/ejbca/mariadb"

    # === Internal ===
    - "{{ data_dir }}/tailscale/state"
    - "{{ data_dir }}/caddy/internal/data"
    - "{{ data_dir }}/caddy/internal/config"
    - "{{ data_dir }}/caddy/internal/certs"
    - "{{ data_dir }}/vaultwarden"
    - "{{ data_dir }}/pihole"
    - "{{ data_dir }}/searxng"
    - "{{ data_dir }}/silverbullet"
    - "{{ data_dir }}/postgresql"
    - "{{ data_dir }}/prometheus"
    - "{{ data_dir }}/grafana"
    - "{{ data_dir }}/n8n/n8n"
    - "{{ data_dir }}/n8n/certs"
    - "{{ data_dir }}/silverbullet/Homelab/Services/n8n/Mounted/"

    # === External ===
    - "{{ data_dir }}/caddy/external/data"
    - "{{ data_dir }}/caddy/external/config"
    - "{{ data_dir }}/caddy/external/certs"

- name: Preconfiguration for EJBCA
  ansible.builtin.include_tasks: ejbca_preconfig.yml
