- name: Ensure logging directory is present
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Documents/server/.logs/cloudflare/"
    state: directory
    mode: '0755'

- name: Schedule Dynamic DNS script
  ansible.builtin.cron:
    name: Update Cloudflare IP
    user: "{{ ansible_user }}"
    minute: "0"
    job: >
      /bin/bash {{ ansible_user_dir }}/Documents/server/terraform/scripts/cloudflare/update_dns.sh
      >> {{ ansible_user_dir }}/Documents/server/.logs/cloudflare/dns_updates.log
