- name: Enable tailscaled service
  ansible.builtin.systemd_service:
    name: tailscaled
    state: started
    enabled: true

- name: Add tailscale up to bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['user_dir'] }}/.bashrc"
    block: |
      tailscale up
    marker: "## {mark} Tailscale setup added by Ansible"
    create: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
